export const devices = (model: string) => ({
  binary_sensor: [
    {
      name: `Connectivity`,
      unique_id: `glinet_${model}_connected`,
      default_entity_id: `glinet_${model}_connected`,
      value_template: `{{ (value_json.network | selectattr('online', 'true') | list | first).online }}`,
      payload_on: true,
      payload_off: false,
      device_class: `connectivity`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json | tojson }}`,
      icon: `mdi:router-network-wireless`,
    },
    {
      name: `Charging`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_charging`,
      default_entity_id: `glinet_${model}_charging`,
      value_template: `{{ value_json.system.mcu.charging_status }}`,
      payload_on: 1,
      payload_off: 0,
      device_class: `battery_charging`,
      entity_category: `diagnostic`,
    },
  ],
  button: [
    {
      name: `Restart`,
      unique_id: `glinet_${model}_restart`,
      default_entity_id: `glinet_${model}_restart`,
      availability: {
        topic: `glinet-${model}/attribute`,
        value_template: `{{ value_json.system.lan_ip }}`,
        payload_available: `192.168.8.1`,
      },
      command_topic: `glinet-${model}/command`,
      payload_press: `restart`,
      device_class: `restart`,
      entity_category: `config`,
    },
    {
      name: `Send SMS`,
      unique_id: `glinet_${model}_send_sms`,
      default_entity_id: `glinet_${model}_send_sms`,
      availability: {
        topic: `glinet-${model}/attribute`,
        value_template: `{{ value_json.modem_info.modems[0].sms_support }}`,
        payload_available: true,
      },
      command_topic: `glinet-${model}/command`,
      command_template: `send_sms={"msg":"{{ states('text.glinet_${model}_sms_message') }}","to":"{{ states('text.glinet_${model}_sms_recipient') }}"}`,
      icon: `mdi:message-plus`,
    },
  ],
  sensor: [
    {
      name: `Battery`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_battery_charge`,
      default_entity_id: `glinet_${model}_battery_charge`,
      state_class: `measurement`,
      value_template: `{{ value_json.system.mcu.charge_percent }}`,
      device_class: `battery`,
      unit_of_measurement: `%`,
      entity_category: `diagnostic`,
    },
    {
      name: `Cell tower`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_cell_tower`,
      default_entity_id: `glinet_${model}_cell_tower`,
      value_template: `{{ value_json.modem_tower_info.lac }}`,
      icon: `mdi:radio-tower`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.modem_tower_info | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `Connected clients`,
      unique_id: `glinet_${model}_connected_clients`,
      default_entity_id: `glinet_${model}_connected_clients`,
      state_class: `measurement`,
      value_template: `{{ value_json.client[0].wireless_total | int(0) }}`,
      icon: `mdi:wifi-star`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.client[0] | tojson }}`,
    },
    {
      name: `Connection text`,
      unique_id: `glinet_${model}_connection_text`,
      default_entity_id: `glinet_${model}_connection_text`,
      value_template: `{{ {2:"2G",3:"3G",4:"4G",41:"4G+",5:"5G",51:"5G+"}[value_json.modem_status.modems[0].simcard.signal.mode] }}`,
      icon: `mdi:signal-4g`,
    },
    {
      name: `CPU temperature`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_cpu_temperature`,
      default_entity_id: `glinet_${model}_cpu_temperature`,
      state_class: `measurement`,
      value_template: `{{ value_json.system.cpu.temperature }}`,
      device_class: `temperature`,
      unit_of_measurement: `°C`,
      icon: `mdi:thermometer`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ { "load_average": value_json.system.load_average } | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `Data use (TX)`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_data_usage_tx`,
      default_entity_id: `glinet_${model}_data_usage_tx`,
      state_class: `total_increasing`,
      value_template: `{{ value_json.modem_status.modems[0].network.tx }}`,
      device_class: `data_size`,
      unit_of_measurement: `B`,
      icon: `mdi:counter`,
      entity_category: `diagnostic`,
    },
    {
      name: `Data use (RX)`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_data_usage_rx`,
      default_entity_id: `glinet_${model}_data_usage_rx`,
      state_class: `total_increasing`,
      value_template: `{{ value_json.modem_status.modems[0].network.rx }}`,
      device_class: `data_size`,
      unit_of_measurement: `B`,
      icon: `mdi:counter`,
      entity_category: `diagnostic`,
    },
    {
      name: `Data use`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_data_usage`,
      default_entity_id: `glinet_${model}_data_usage`,
      state_class: `total_increasing`,
      value_template: `{{ ((value_json.modem_status.modems[0].network.tx or 0) + (value_json.modem_status.modems[0].network.rx or 0)) or (value_json.modem_status.modems[0].network.traffic_total) }}`,
      device_class: `data_size`,
      unit_of_measurement: `B`,
      icon: `mdi:counter`,
      entity_category: `diagnostic`,
    },
    {
      name: `Data used (GiB)`,
      unique_id: `glinet_${model}_data_usage_gb`,
      default_entity_id: `glinet_${model}_data_usage_gb`,
      state_class: `total_increasing`,
      value_template: `{{ ((((value_json.modem_status.modems[0].network.tx or 0) + (value_json.modem_status.modems[0].network.rx or 0)) or value_json.modem_status.modems[0].network.traffic_total) / 1073741824) | round(3) }}`,
      device_class: `data_size`,
      unit_of_measurement: `GiB`,
      icon: `mdi:counter`,
    },
    {
      name: `Flash free`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_flash_memory_free`,
      default_entity_id: `glinet_${model}_flash_memory_free`,
      state_class: `measurement`,
      value_template: `{{ value_json.system.flash_free }}`,
      device_class: `data_size`,
      unit_of_measurement: `B`,
      icon: `mdi:harddisk`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ { "flash_total": value_json.system.flash_total, "flash_app": value_json.system.flash_app } | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `IP location`,
      unique_id: `glinet_${model}_ip_location`,
      default_entity_id: `glinet_${model}_ip_location`,
      value_template: `{{ value_json.ip_location.query }}`,
      availability: {
        topic: `glinet-${model}/attribute`,
        value_template: `{{ value_json.ip_location.status }}`,
        payload_available: `success`,
      },
      icon: `mdi:ip`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.ip_location | tojson }}`,
    },
    {
      name: `Memory available`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_available`,
      default_entity_id: `glinet_${model}_memory_available`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_free + value_json.system.memory_buff_cache) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      entity_category: `diagnostic`,
    },
    {
      name: `Memory buff/cache`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_buff_cache`,
      default_entity_id: `glinet_${model}_memory_buff_cache`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_buff_cache) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      entity_category: `diagnostic`,
    },
    {
      name: `Memory free`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_free`,
      default_entity_id: `glinet_${model}_memory_free`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_free) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ { "memory_total": value_json.system.memory_total, "memory_buff_cache": value_json.system.memory_buff_cache } | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `Memory total`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_total`,
      default_entity_id: `glinet_${model}_memory_total`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_total) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      entity_category: `diagnostic`,
    },
    {
      name: `Memory total used`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_total_used`,
      default_entity_id: `glinet_${model}_memory_total_used`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_total - value_json.system.memory_free - value_json.system.memory_buff_cache) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      entity_category: `diagnostic`,
    },
    {
      name: `Memory used`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_memory_used`,
      default_entity_id: `glinet_${model}_memory_used`,
      state_class: `measurement`,
      value_template: `{{ ((value_json.system.memory_total - value_json.system.memory_free) / 1048576) | round(2) }}`,
      device_class: `data_size`,
      unit_of_measurement: `MiB`,
      icon: `mdi:memory`,
      entity_category: `diagnostic`,
    },
    {
      name: `Network`,
      unique_id: `glinet_${model}_connected_network`,
      default_entity_id: `glinet_${model}_connected_network`,
      value_template: `{{ value_json.modem_status.modems[0].simcard.carrier }}`,
      icon: `mdi:cellphone-text`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.modem_status.modems[0] | tojson }}`,
    },
    {
      name: `Router`,
      unique_id: `glinet_${model}_router`,
      default_entity_id: `glinet_${model}_router`,
      value_template: `{{ value_json.system.lan_ip }}`,
      icon: `mdi:router-wireless-settings`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.system | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `RSSI`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_signal_strength`,
      default_entity_id: `glinet_${model}_signal_strength`,
      state_class: `measurement`,
      value_template: `{{ value_json.modem_status.modems[0].simcard.signal.rssi }}`,
      device_class: `signal_strength`,
      unit_of_measurement: `dBm`,
      entity_category: `diagnostic`,
      icon: `mdi:signal-distance-variant`,
    },
    {
      name: `Service type`,
      unique_id: `glinet_${model}_service_type`,
      default_entity_id: `glinet_${model}_service_type`,
      value_template: `{{ value_json.modem_status.modems[0].simcard.signal.network_type }}`,
      icon: `mdi:radio-tower`,
    },
    {
      name: `Signal`,
      unique_id: `glinet_${model}_signal`,
      default_entity_id: `glinet_${model}_signal`,
      state_class: `measurement`,
      value_template: `{{ value_json.modem_status.modems[0].simcard.signal.strength }}`,
      icon: `mdi:signal`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.modem_status.modems[0].simcard | tojson }}`,
    },
    {
      name: `Started`,
      unique_id: `glinet_${model}_started`,
      default_entity_id: `glinet_${model}_started`,
      value_template: `{{ (as_timestamp(now()) | round(0) - value_json.system.uptime) | as_datetime }}`,
      device_class: `timestamp`,
      icon: `mdi:clock`,
      entity_category: `diagnostic`,
    },
    {
      name: `Unread SMS`,
      unique_id: `glinet_${model}_unread_sms`,
      default_entity_id: `glinet_${model}_unread_sms`,
      state_class: `measurement`,
      value_template: `{{ value_json.modem_sms.list | selectattr('type', 'equalto', 2) | selectattr('status', 'equalto', 0) | list | length }}`,
      icon: `mdi:message-text-clock`,
      payload_on: true,
      payload_off: false,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{ "messages": {{ value_json.modem_sms.list | selectattr('type', 'equalto', 2) | sort(attribute='date', reverse=True) | list | tojson }} }`
    },
    {
      name: `WAN interface`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_wan_interface`,
      default_entity_id: `glinet_${model}_wan_interface`,
      value_template: `{{ value_json.network | selectattr('online', 'true') | map(attribute='interface') | list | first }}`,
      icon: `mdi:help-network-outline`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{%- set a = namespace(value={}) -%}{%- for n in value_json.network|list -%}{%- set a.value = dict(a.value, **{n.interface: { "online": n.online, "up": n.up }}) -%}{%- endfor %}{{ a.value | tojson }}`,
      entity_category: `diagnostic`,
    },
    {
      name: `WWAN band`,
      enabled_by_default: false,
      unique_id: `glinet_${model}_wwan_band`,
      default_entity_id: `glinet_${model}_wwan_band`,
      value_template: `{{ value_json.modem_cells_info.cells[0].mode }}`,
      icon: `mdi:signal-variant`,
      json_attributes_topic: `glinet-${model}/attribute`,
      json_attributes_template: `{{ value_json.modem_cells_info.cells[0] | tojson }}`,
      entity_category: `diagnostic`,
    },
  ],
  text: [
    {
      name: `SMS message`,
      unique_id: `glinet_${model}_sms_message`,
      default_entity_id: `glinet_${model}_sms_message`,
      availability: {
        topic: `glinet-${model}/attribute`,
        value_template: `{{ value_json.modem_info.modems[0].sms_support }}`,
        payload_available: true,
      },
      command_topic: `glinet-${model}/command`,
      command_template: `set_sms_msg={{ value }}`,
      state_topic: `glinet-${model}/sms/message`,
      value_template: "{{ value }}",
      icon: `mdi:message-text`,
    },
    {
      name: `SMS recipient`,
      unique_id: `glinet_${model}_sms_recipient`,
      default_entity_id: `glinet_${model}_sms_recipient`,
      availability: {
        topic: `glinet-${model}/attribute`,
        value_template: `{{ value_json.modem_info.modems[0].sms_support }}`,
        payload_available: true,
      },
      command_topic: `glinet-${model}/command`,
      command_template: `set_sms_to={{ value }}`,
      state_topic: `glinet-${model}/sms/recipient`,
      value_template: "{{ value }}",
      icon: `mdi:message-question`,
    },
  ],
});
