name: Docker build

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  APP_IMAGE: ghcr.io/${{ github.repository }}/${{ github.ref_name }}/app

jobs:
  build:
    name: Build image and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'

      - name: Log into container registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image and push to ${{ env.APP_IMAGE }}:latest
        id: build
        env:
          BUILD_IMAGE: ${{ env.APP_IMAGE }}:build-${{ github.run_number }}
          LATEST_IMAGE: ${{ env.APP_IMAGE }}:latest
        run: |
          docker build -t $LATEST_IMAGE -t $BUILD_IMAGE .
          docker push --all-tags ${{ env.APP_IMAGE }}